### ISSUE TITLE
Ludo 0.52-0.57 Immediate Exit on Windows 10 Pro x64

### ISSUE THREAD

**Issue by Xerxes3rd** [libretro/ludo#195] opened 2019-04-17 17:56 UTC
Starting with Ludo 0.52, the main window briefly displays, then disappears.  Ludo 0.51 back through 0.42 shows normally.  Using Windows 10 Pro Version 1803 (10.0.17134), Intel Core i7-4600U (Intel HD Graphics 4400).  I don't see any errors in the Windows Application Event Logs.

**Comment by kivutar** [comment] 2019-04-18 03:41
Can you try to set `"video_filter": "nearest",` manually in `~/.ludo/settings.json`?

**Comment by Xerxes3rd** [comment] 2019-04-19 14:38
No change.  I noticed that pre-5.2 versions will remove the `"video_filter"` setting from `settings.json` (I assume this is expected behavior).

**Comment by kivutar** [comment] 2019-04-20 03:32
OK, so maybe it's not due to the `video_filter`... these are the differences between 0.5.1 and 0.5.2:

```
commit a8c8a95ec821995c96dbc5e825c2cef759a4623b (tag: v0.5.2)
Author: Jean-André Santoni <jean.andre.santoni@gmail.com>
Date:   Fri Mar 1 22:35:10 2019 +0700

    Sharp-bilinear filter (#168)

    * Sharp-bilinearcshader

    * Implement incomplete RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO

    * Update the uniform in the Refresh callback. Fixes snes9x

    * Video filter setting

    * Black transparent overlay

commit 4892dd04ddaed31ca867997a5fcfc8be7b31affc
Author: Jean-André Santoni <jean.andre.santoni@gmail.com>
Date:   Fri Mar 1 11:24:29 2019 +0700

    Don't call GetSystemAVInfo on every frame (#175)

    * Don't call GetSystemAVInfo on every frame

    * Implement RETRO_ENVIRONMENT_SET_GEOMETRY

    * Revert unneeded screenshot changes

    * Reduce cyclo of environment callback

commit b04fa11c79da33158b36269aaf901c3d4892e889 (tag: v0.5.1)
```

**Comment by Xerxes3rd** [comment] 2019-04-20 17:48
So the next step would probably be to set up a development environment, compile from source and debug it?  I've not done Go development before, so it might take me a bit to get the environment and libraries all ready.

**Comment by kivutar** [comment] 2019-04-21 16:08
Yep, and it might not be so simple, as setting up the dev env may even fix the bug for you, making it impossible to reproduce. But if you have time, it's worth trying.

In fact you're not the only one that is affected by this bug on Windows. It's quite a major issue, as Windows is the favorite platform of gamers.

In case you have some time for this, the reference to setup the dev env are there in the travis file https://github.com/libretro/ludo/blob/master/.travis.yml#L80-L95
They are based on git bash, which is the bash interpreter that you get when setting up git on Windows.

**Comment by Xerxes3rd** [comment] 2019-04-21 16:29
That had crossed my mind too.  I suppose I could set a restore point, then re-test the downloaded binary at each step of the dev env setup process.

One more note- I'm running this on a PC that's joined to a corporate domain, with some loose group policies enforced.  Running Ludo as Administrator has no effect either.

**Comment by Braetzelbush** [comment] 2019-04-25 18:53
I have tested on my laptops
it seems to be a problem with the intel graphics or the openGL version.
i had the same problem with my  i7-4600U (HD Graphics 4400) and i7-7700HQ (HD 630)
the 7700HQ has dual graphics, so i change to the MX150. No Problem on the Nvidia GPU.

it works with the Intel GPUs, if you set the `"video_gl_version"` to `2.1` or lower.

**Comment by kivutar** [comment] 2019-04-28 05:53
@Xerxes3rd can you try this `2.1` workaround?

I'm reluctant to set 2.1 as default because text doesn't show on OSX with 2.1 for some reasons.

**Comment by Xerxes3rd** [comment] 2019-04-29 18:26
@kivutar Yep, the workaround works for me as well.

**Comment by kivutar** [comment] 2019-05-02 02:32
OK that's a good hint. Now I need to find what change in the code caused this regression.

Could it be the 

```
	if state.Global.CoreRunning {
		vid.DrawRect(0, 0, float32(w), float32(h), 0, video.Color{R: 0, G: 0, B: 0, A: 0.85})
	}
```

added in menu.go `Render` func?

**Comment by rekuhs** [comment] 2019-08-28 12:53
I have the same issue

**Comment by jholloway** [comment] 2019-09-05 17:18
I don't know if it's helpful, but I can also confirm I have this same issue running Ludo 0.8.2 on Windows 10 Home x64 1903 on Surface Pro 6 (Intel UHD Graphics 620). Using the `video_gl_version` workaround allows Ludo to launch.

**Comment by kivutar** [comment] 2019-10-14 05:58
Maybe we should not configure any windows hints in glfw, and let the lib guess what's the best configuration.
Problem with this: it selects 2.1 for OSX, which breaks the fonts.

**Comment by jjfmz42015** [comment] 2019-10-15 02:50
Hmmm odd very similar setup here no issues. Try going to Intel website and upgrade video driver

**Comment by kivutar** [comment] 2019-10-20 14:04
Please somebody try this banch https://github.com/libretro/ludo/pull/270 to see if it fixes the issue

**Comment by kivutar** [comment] 2019-10-26 07:48
I've merged this branch and made a new release, please tell me if it fixed the bug.

**Comment by marcmam2** [comment] 2019-10-28 00:44
I'm still experiencing this on 0.9.2

**Comment by ImJezze** [comment] 2019-10-28 19:04
I have the same issue with 0.9.2.

I also tried several older versions (0.5.1, 0.5.2, 0.6.0, 0.8.0, 0.8.9, 0.9.0, 0.9.1) and for me the issue starts with 0.9.1

Windows 10 Pro 64-bit (1903, Build 18362.418)
Nvidia NVIDIA GeForce GTX 970 (440.97)

**Comment by kivutar** [comment] 2019-10-29 03:10
OK so we have at least 2 different issues there.

One started from v0.5.2 and may be related so the new sharp bilinear shader. Workaround here is to force GL 2.1.

Another issue has been introduced at v0.9.1 where I introduced a change to let the driver guess what GL version to use. I was expecting this to fix the first issue, but it's causing more harm.

**Comment by kivutar** [comment] 2019-10-30 06:33
Please everybody try v0.9.4

**Comment by ImJezze** [comment] 2019-10-30 08:41
I tested 0.9.4 on another machine that has two integrated graphics cards and tested each separately, by deactivating the other.

Windows 10 Enterprise 64-bit (1803, Build 17134.1069)
Intel UHD Graphics 630 (0.5.1 working, 0.5.2 not working, 0.9.4 not working)
NVIDIA Quadro P2000 (0.9.0 working, 0.9.1 not working, 0.9.4 not working)

I'll test it later this day on my other machine with the NVIDIA GeForce.

**Comment by rekuhs** [comment] 2019-10-30 11:11
I've just tried 0.9.4 and unfortunately there's no change. Same machine/specs as before.
- Win 10 Pro x64 (1903)
- Core i5-7200U
- 8GB RAM
- nVidia MX150

**Comment by kivutar** [comment] 2019-10-30 11:42
OK, then there is really something wrong that happened between v0.5.1 and v0.5.2: https://github.com/libretro/ludo/compare/v0.5.1...v0.5.2

And I think that it could be the sharp bilinear shader, so I'm going to release a version without it, because I need to make sure that it's the cause.

**Comment by kivutar** [comment] 2019-10-30 12:03
v0.9.5 is up, where I've completely removed the sharp bilinear shader, and also the crt shader that wasn't there in v0.5.1.

My bet is that the compilation of these shaders was failing for whatever reasons and that it was crashing the program on startup. I do really hope that it fixes it, because if not, it's going to be way trickier to fix.

**Comment by ImJezze** [comment] 2019-10-30 19:00
No change with 0.9.5, sorry.

**Comment by kivutar** [comment] 2019-10-31 03:25
This version fixes an OpenGL error on startup, and print other possible errors:

https://github.com/libretro/ludo/releases/download/v0.9.6/Ludo-Windows-x86_64-0.9.6.zip

**Comment by kivutar** [comment] 2019-10-31 05:54
And this one fixes another OpenGL error: https://github.com/libretro/ludo/releases/download/v0.9.7/Ludo-Windows-x86_64-0.9.7.zip

**Comment by ImJezze** [comment] 2019-10-31 11:54
I tested both new builds and the 0.9.1 issue is still there. I currently cannot speak for the 0.5.2 issue, because I couldn't test it with an Intel GPU yet.

Also, I don't see an error message. Would it be shown as a message box or is it logged into a file?

**Comment by kivutar** [comment] 2019-10-31 13:34
It would appear only when launching the program from a terminal.

**Comment by kivutar** [comment] 2019-11-12 06:14
v0.9.13 should fix half of the bugs here. Especially the bug on your NVIDIA Quadro P2000 @ImJezze

**Comment by ImJezze** [comment] 2019-11-12 18:20
I can confirm that with v0.9.13 this issue is fix for my NVIDIA GeForce GTX 970 and probably also for the NVIDIA Quadro P2000, which I can test tomorrow.

**Comment by Xerxes3rd** [comment] 2019-11-12 20:22
Just tried it on the same hardware as listed in the original port (albeit with Windows 10 Pro x64 v1909 now), and it started up just fine!  v0.9.13 rocks, and it would appear that you can finally close this issue!

**Comment by ImJezze** [comment] 2019-11-13 14:13
Also works for Intel UHD Graphics 630 and NVIDIA Quadro P2000.

**Comment by kivutar** [comment] 2019-11-13 23:53
Cool. I still don't understand what caused the issue in 0.5.2, but if it works....

**Closed by kivutar** 2019-11-13 23:53 UTC
Labels: bug, help wanted, high-priority
