### ISSUE TITLE
Scanning folder with NES games not working

### ISSUE THREAD

**Issue by bycrean** [libretro/ludo#446] opened 2021-07-01 18:24 UTC
After successfully scanning folders with Super Nintendo, Genesis and TurboGrafx-16 games, I tried scanning a folder with NES games (.nes file format). However, Ludo showed the message: "Done scanning. 0 new games found." It is worth noting that they are not already imported, since no NES icon appears on the start screen of Ludo. Ironically, when I load the NES games manually by first selecting 'Load Core' and then 'Load Game', I can play the game.

**Comment by johnnyq** [comment] 2021-07-03 18:18
@bycrean You will need to get the no-intro versions of nes rom packs for Ludo to scan properly in.

see here https://jean-andre-santoni.gitbook.io/ludo/launching-games

**Comment by bycrean** [comment] 2021-07-04 07:27
@johnnyq Thank you. However, I looked at the link and did some reading online and still don't understand what a "No-Intro" ROM is or how I can see if a given ROM is "No-Intro" or not. The articel you linked could be more specific in this regard. All I can say is that I used the same ROMs with OpenEmu and it worked flawlessly. Also, as I mentioned before, I can manually load the ROMs with Ludo and play them. So I'm still confused.

**Comment by johnnyq** [comment] 2021-07-04 16:16
@bycrean I know it is confusing because no one gives an explanation what no-into roms are. Basically they are clean roms without additions, in the past rippers would add their signature intro screen before the title screen. That where no-intro comes into play its guarenteed clean roms set.

Do a quick google search for no-intro nes rom set and download the bulk and choose what you want out of the bulk download. These are known to work.

**Comment by kivutar** [comment] 2021-07-07 06:38
Right, these are the NES roms we support: https://raw.githubusercontent.com/kivutar/ludo-database/kivutar/xml/Nintendo%20-%20Nintendo%20Entertainment%20System.dat

**Comment by bycrean** [comment] 2021-07-08 08:15
Thanks for replies. However, I still don't know why Ludo doesn't let me add my NES roms to my library even though I can start them manually (through 'Load Core' and 'Load Game') and even though I could add them to my OpenEmu library (when I was still using OpenEmu). Wouldn't it be possible for Ludo's ROM scanner to support other ROMs as well or is that not intended?

**Comment by kivutar** [comment] 2021-07-11 09:02
Yeah I think it's a valid feature request. This checksum based scanner is clearly showing its limits.

Even if we start adding more databases, for example GoodTools, I'm afraid it will never be enough.. There are new homebrews every months, new fan translations, new romhacks.

The problem is that extension based scanners are also limited. There is not a 1 to 1 mapping between extensions and systems.

So maybe a smart mix of both.

**Comment by kivutar** [comment] 2021-07-18 05:30
Closed in favor of https://github.com/libretro/ludo/issues/453

**Closed by kivutar** 2021-07-18 05:30 UTC
Labels: question
