### ISSUE TITLE
Ludo-Windows-x86_64-0.8.1 not starting ?

### ISSUE THREAD

**Issue by MopheusDG** [libretro/ludo#221] opened 2019-08-25 00:53 UTC
Hi, wanna give Ludo a try but doesn't start at all, no errors, no logs, nothing.

OS: Windows 7 64 Bits (Latest updates installed).
Version of LUDO: Ludo-Windows-x86_64-0.8.1 (Also tried 0.7.3 without luck, same issue).
HW: Lenovo E420 (i5 with Intel Graphics and 8 Gb of RAM).

Anyway to check for what could be missing ?

Thanks.

**Comment by MopheusDG** [comment] 2019-08-25 00:55
Tried latest release 0.8.1 and same issue.

**Comment by kivutar** [comment] 2019-08-27 15:38
I think this is a duplicate of https://github.com/libretro/ludo/issues/195
Thanks for reporting.

**Closed by kivutar** 2019-08-27 15:38 UTC
