### ISSUE TITLE
Bug: PS4 Controller support in LudOS

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#273] opened 2019-10-23 17:25 UTC
I updated to the latest LudOS on Pi3b+ and was using a PS4 Controller Wired, now the controller does not work. I attached an image below it looks like it detects as a wireless controller now and also detects the touchpad on the PS4 controller. This is the message I get
![2019-10-23 13-23-09-1](https://user-images.githubusercontent.com/1812594/67418232-6895e980-f598-11e9-9c2e-5e45144a7ff3.JPG)

**Comment by johnnyq** [comment] 2019-10-23 17:31
ill test it on my linux mint 19.2 box and see if it works there and report back

**Comment by johnnyq** [comment] 2019-10-23 17:43
It works on my linux mint 19.2 with 5.0 Kernel

![2019-10-23 13-42-02-1](https://user-images.githubusercontent.com/1812594/67419598-fecb0f00-f59a-11e9-8545-08dba08580bc.JPG)

**Comment by kivutar** [comment] 2019-10-24 04:53
Yep, I've noticed this bug yesterday when testing.

I think we should find a udev rule so that the touchpad version should be tagged as a touchpad and not a controller.

This is a high priority bug.

**Comment by johnnyq** [comment] 2019-10-26 20:07
hello @kivutar I added the file and rebooted but still no go I get the same message

**Comment by kivutar** [comment] 2019-10-28 16:17
OK thanks

**Comment by johnnyq** [comment] 2019-11-20 19:04
I wonder if updating the Linux Kernel to 5.3 will fix this? or disabling touchpad support all together, that way it doesn't detect the touchpad on the PS4 controller as a separate controller. I also noticed that it detects the touchpad on the PS4 controller as controller 0 and the gamepad part as controller 1. I wonder if they could be swapped, just throwing some ideas out there.

**Comment by kivutar** [comment] 2019-11-21 04:04
I don't know yet if the bug is caused by a change in the kernel or the switch to GLFW 3.3

**Comment by kivutar** [comment] 2019-11-21 06:37
Can you try these rules please?

```
SUBSYSTEM=="input", ATTRS{name}=="*Controller Motion Sensors", RUN+="/bin/rm %E{DEVNAME}", ENV{ID_INPUT_JOYSTICK}=""
SUBSYSTEM=="input", ATTRS{name}=="*Controller Touchpad", RUN+="/bin/rm %E{DEVNAME}", ENV{ID_INPUT_JOYSTICK}=""
```

**Comment by johnnyq** [comment] 2019-11-21 06:44
okay I will give this a shot right now

**Comment by johnnyq** [comment] 2019-11-21 06:52
I added the following and rebooted, it did not work but I did get something different take a look
It disconnected controller 0 which is the touchpad on the PS4 but it doesnt switch Jostick #1 to 0.


![2019-11-21 01-50-27-1](https://user-images.githubusercontent.com/1812594/69314174-7a06fb80-0c01-11ea-861f-16e2b1173775.JPG)

**Comment by kivutar** [comment] 2019-11-21 10:53
It only happens on LudOS so far, I have a Manjaro with a 4.19 kernel and it's not happening there.
So I think it must be a kernel configuration to change.

**Comment by ofuangka** [comment] 2019-11-30 01:06
FWIW I have a similar issue on ArchLinux, not LudOS.  The difference was that for me, the name of the devices that appear are "Wireless Controller" and "Wireless Controller Touchpad".  For whatever reason, removing my user from the "input" group resolved the issue.  @kivutar you might be able to reproduce it by adding yourself _to_ the "input" group, although it's really just a guess.

**Comment by johnnyq** [comment] 2020-01-31 03:36
@ofuangka ill give this a shot

**Comment by johnnyq** [comment] 2020-02-29 04:26
still no go

**Comment by kivutar** [comment] 2020-09-05 17:48
Now plugging a DS4 will crash Ludo, some changes made the issue worse.

**Comment by kivutar** [comment] 2020-12-05 11:43
The bug seems to be in glfw:

```
LudOS:~ # ludo -v
2020/12/05 11:26:29 [Input]: Joystick #0 plugged: Sony Interactive Entertainment Wireless Controller Touchpad but not configured.
panic: InvalidValue: Invalid button in gamepad mapping 030000004c050000cc09000011810000 (PS4 Controller)

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/error.go:174 +0x1a4
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/error.go:185
github.com/go-gl/glfw/v3.3/glfw.PollEvents()
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/window.go:950 +0x30
main.runLoop(0x1c5a1c0, 0x1d00150)
	/home/runner/work/ludo/ludo/main.go:34 +0xbc
main.main()
	/home/runner/work/ludo/ludo/main.go:129 +0x460
```

Maybe related to 
https://github.com/hajimehoshi/ebiten/issues/1229
https://github.com/glfw/glfw/issues/1583
https://github.com/glfw/glfw/issues/1447

**Comment by kivutar** [comment] 2021-05-29 11:29
It's because DS4 have a touchpad and a microphone. For some reasons GLFW tries to use the touchpad or microphone as a pad.

**Comment by kivutar** [comment] 2021-06-05 06:36
See also https://github.com/glfw/glfw/issues/1763

**Comment by kivutar** [comment] 2021-07-17 05:00
I bumped GLFW binding, at least now it's not crashing anymore.

The touchpad is still being detected before the pad itself, which prevents the pad to be assigned to the right person.

Now trying to remote the touchpad support at the udev level.

**Comment by kivutar** [comment] 2021-07-18 05:06
Finally fixed

**Closed by kivutar** 2021-07-18 05:06 UTC
Labels: bug, high-priority
