### ISSUE TITLE
(Ludo Desktop Linux) game added double playlist entries bug

### ISSUE THREAD

**Issue by ghost** [libretro/ludo#421] opened 2021-05-18 20:46 UTC
Desktop PC
OS: Linux Mint 20.1
Ludo: Ludo-Linux-x86_64-0.14.0  (bug also in older version)

When adding a rom to the playlist for Final Burn Neo it added 2 entries, even the thumbnails had two entries for my one rom. For these CSV files can they be opened with other programs for ease of use?

FBNeo CSV file
[FBNeo - Arcade Games.csv](https://github.com/libretro/ludo/files/6504345/FBNeo.-.Arcade.Games.csv)

**Comment by kivutar** [comment] 2021-05-20 11:17
Thanks, will look into it

**Comment by johnnyq** [comment] 2021-07-03 18:39
I have the same issue as well on LUDOS for Raspberry pi 3b+

**Comment by kivutar** [comment] 2021-07-24 12:16
I can reproduce

**Comment by igoracmelo** [comment] 2024-03-13 20:17
@kivutar This happens because the function `FindByCRC` doesn't stop on first match.
I could make a PR to end the function on the first match, but I don't know if that is the desired behavior...

**Comment by tompruitt** [comment] 2024-03-30 14:01
This should be fixed.
Do you want to check if its fixed, or can this be closed? @ghost

**Comment by igoracmelo** [comment] 2024-03-30 22:49
Should be solved by #540

**Closed** 2024-05-24 14:04 UTC
Labels: bug
