### ISSUE TITLE
Screen Tearing Occational frame skips in Emulators

### ISSUE THREAD

**Issue by johnnyq** [libretro/ludo#237] opened 2019-09-02 15:51 UTC
I noticed there has been some screen tearing mostly with SNES games especially contra 3 but I have noticed it in sega genesis and nintendo as well. I also noticed what appears to be the occational screen frame skipping. This was tested on the Raspberry Pi 4 i will test on the 3b+ to see if I get the same result

**Comment by kivutar** [comment] 2019-09-05 13:21
I'm also experiencing this, but only on some TV.

**Comment by johnnyq** [comment] 2019-09-26 18:20
Yeah same here, it doesn't affect me on my Sony TV but does happen on my Asus monitor

**Comment by kivutar** [comment] 2019-09-27 09:53
Then it's going to be difficult to investigate. I have no idea how to debug this.
We can hope that a LibreELEC update or a GLFW update fixes it.

**Comment by kivutar** [comment] 2019-10-03 14:45
It happens a lot with Genesis games.

**Comment by johnnyq** [comment] 2019-10-08 04:20
This appears to be fixed on my end with the latest LudOS

**Comment by kivutar** [comment] 2019-10-11 02:50
Even with Genesis games?

**Comment by johnnyq** [comment] 2020-01-14 05:41
yes I started noticing this more im not sure what causes it

**Comment by kivutar** [comment] 2021-07-18 05:14
Close as duplicate of https://github.com/libretro/ludo/issues/344

**Closed by kivutar** 2021-07-18 05:14 UTC
Labels: bug, high-priority
