### ISSUE TITLE
Mac OS X issues

### ISSUE THREAD

**Issue by Fatty69420** [libretro/ludo#151] opened 2019-02-10 20:45 UTC
Doesn’t work on Mac OS X Mojave,
Failed to find suitable pixel format

**Comment by fmaida** [comment] 2019-02-10 22:05
That's strange, I'm using Ludo 0.3.5 on a MacBook Air running Mojave and it's working.

**Comment by Fatty69420** [comment] 2019-02-10 22:13
That’s strange, just opens and closes for me.
Even using it with wine just doesn’t work.

**Comment by Fatty69420** [comment] 2019-02-10 22:15
But I’m using ludo 0.3.7 so :/

**Comment by Fatty69420** [comment] 2019-02-10 22:16
Just tried 0.3.5 and it also doesn’t work

**Comment by kivutar** [comment] 2019-02-11 03:58
Can you `/Applications/Ludo.app/Contents/MacOS` and `./ludo -v`
To have an error log?

**Comment by Fatty69420** [comment] 2019-02-11 04:12
In the morning

**Comment by Fatty69420** [comment] 2019-02-11 22:53
Sorry that I am responding so late, got home from class a while ago, let me run that.

**Comment by Fatty69420** [comment] 2019-02-11 22:56
![Image](https://i.imgur.com/hySemGO.jpg)

**Comment by kivutar** [comment] 2019-02-12 01:16
Ah that's something new...
What core were you launching? Or it was just the UI?

**Comment by kivutar** [comment] 2019-02-12 01:23
Try things like:

```
./ludo -glver=4.5
```

```
./ludo -glver=4.1
```

```
./ludo -glver=3.2
```

```
./ludo -glver=3.0
```

```
./ludo -glver=2.1
```

Just to see if one of them works. Please.

**Comment by Fatty69420** [comment] 2019-02-12 11:35
I will later today

**Comment by kivutar** [comment] 2019-02-12 13:07
Apparently, many users are experiencing similar issues with GLFW based programs on OSX.

It would be good for us to know your hardware, especially the graphic card.

**Comment by Fatty69420** [comment] 2019-02-12 14:49
Intel core i7
16GB ram
GTX 950
1Tb hard disk
Mac OS X Mojave

**Comment by kivutar** [comment] 2019-02-12 16:38
OK, I'll try this https://stackoverflow.com/questions/27365099/nsgl-failed-to-create-opengl-pixel-format

**Comment by kivutar** [comment] 2019-02-14 14:49
@Fatty69420 please try http://static.kivutar.me/Ludo-OSX-x86_64-stencil8bit.dmg

**Comment by Fatty69420** [comment] 2019-02-15 12:16
I will when I get home

**Comment by Fatty69420** [comment] 2019-02-15 23:55
im going to try it right now

**Comment by Fatty69420** [comment] 2019-02-15 23:56
```
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: NSGL: Failed to find a suitable pixel format
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: NSGL: Failed to find a suitable pixel format

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.2/glfw.acceptError(0xc0000b7ce8, 0x2, 0x2, 0x0, 0x0)
	/Users/kivutar/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/error.go:177 +0x1ba
github.com/go-gl/glfw/v3.2/glfw.CreateWindow(0x3c0, 0x21c, 0x43ef113, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/kivutar/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/window.go:288 +0x17b
github.com/libretro/ludo/video.(*Video).Configure(0xc0004d4080, 0xc0004d4000)
	/Users/kivutar/ludo/video/video.go:145 +0x9a
github.com/libretro/ludo/video.Init(0xc000092800, 0xc000092670, 0x3, 0x0)
	/Users/kivutar/ludo/video/video.go:60 +0x63
main.main()
	/Users/kivutar/ludo/main.go:94 +0x3fc
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by kivutar** [comment] 2019-02-16 08:10
OK, so it was not what I initially thought.

Though one. I'm going to have to borrow a few laptops from friends and family to test, because I feel like shooting in the dark..

**Comment by kivutar** [comment] 2019-03-24 05:07
What was the result for `./ludo -glver=2.1` ?

**Comment by kivutar** [comment] 2019-04-28 05:57
Closing this for now, as I can't reproduce and don't get replies after a month.

**Closed by kivutar** 2019-04-28 05:57 UTC
Labels: bug, help wanted, question
