### ISSUE TITLE
N64 games and Wario Land 4 say "failed to load the game" opening them

### ISSUE THREAD

**Issue by ExGuestCJ** [libretro/ludo#507] opened 2023-07-05 23:31 UTC

**Comment by kivutar** [comment] 2023-08-06 14:37
It's because ludo doesn't yet support mupen64plus on linux or osx.

Ludo doesn't have the hardware acceleration part of the libretro API.

The windows version of mupen is built with LLE and the software renderer, the linux version apparently not yet.

Either I'll add hardware acceleration in Ludo, either I'll ask the maintainer of mupen64_plus_next to build with LLE.

**Comment by ExGuestCJ** [comment] 2023-08-06 17:02
> It's because ludo doesn't yet support mupen64plus on linux or osx.
> 
> Ludo doesn't have the hardware acceleration part of the libretro API.
> 
> The windows version of mupen is built with LLE and the software renderer, the linux version apparently not yet.
> 
> Either I'll add hardware acceleration in Ludo, either I'll ask the maintainer of mupen64_plus_next to build with LLE.

but im using windows

**Comment by kivutar** [comment] 2024-03-03 11:07
Probably fixed on Windows now. On Linux soon.

**Comment by igoracmelo** [comment] 2024-03-13 20:29
Is it a duplicate of #4?

**Comment by kivutar** [comment] 2024-05-24 14:06
Not really, the core should start using the software renderer. I think this issue was created before we added mupen in ludo.

**Closed** 2024-05-24 14:06 UTC
